"""Backward compatibility tests for inference module.

These tests verify that the new InferenceRunner produces output consistent
with the original run_protein_mpnn.py implementation.

There are two types of tests:
1. TestInferenceMatchesOriginal - Compares new code against the ORIGINAL code in run/
   The fixture was generated using scripts/generate_original_fixtures.py
2. TestInferenceRegression - Ensures the new code is deterministic and doesn't change
   The fixture captures the new code's current behavior for regression testing
"""

from __future__ import annotations

import json

import pytest

from proteinmpnn.inference import InferenceRunner
from proteinmpnn.utils.constants import ROOT_DIR, WEIGHTS_PATH

# Test data paths
DATA_DIR = ROOT_DIR / "data" / "pdbs"
EXAMPLES_DIR = ROOT_DIR / "examples"
FIXTURES_DIR = ROOT_DIR / "tests" / "fixtures"


def weights_available() -> bool:
    """Check if model weights are available."""
    return (WEIGHTS_PATH / "v_48_020.pt").exists()


@pytest.mark.skipif(not weights_available(), reason="Model weights not available")
class TestInferenceMatchesOriginal:
    """Test that new inference EXACTLY matches the ORIGINAL run_protein_mpnn.py output.

    The fixture was generated by running the original code in run/ directory
    using scripts/generate_original_fixtures.py. This ensures we compare against
    the true original behavior, not against outputs generated by the new code.

    When properly seeded, both implementations produce IDENTICAL results, confirming
    that the new code is a faithful reimplementation of the original.
    """

    @pytest.fixture
    def original_output(self) -> dict:
        """Load fixture generated from ORIGINAL code in run/."""
        fixture_path = FIXTURES_DIR / "6MRR_inference_original.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new InferenceRunner."""
        import torch

        pdb_path = DATA_DIR / "6MRR.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        # Force CPU to ensure cross-platform reproducibility
        # (torch.randn produces different values on
        # different devices even with same seed)
        runner = InferenceRunner(model_name="v_48_020", device=torch.device("cpu"))
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=3,
            seed=42,
        )
        return {
            "native": {
                "name": result.native.name,
                "score": result.native.score,
                "fixed_chains": result.native.fixed_chains,
                "designed_chains": result.native.designed_chains,
                "model_name": result.native.model_name,
                "sequence": result.native.sequence,
            },
            "sequences": [
                {
                    "temperature": s.temperature,
                    "sample_index": s.sample_index,
                    "score": s.score,
                    "seq_recovery": s.seq_recovery,
                    "sequence": s.sequence,
                }
                for s in result.sequences
            ],
        }

    def test_native_sequence_matches_exactly(
        self, original_output: dict, new_output: dict
    ) -> None:
        """Native sequence must match exactly."""
        assert original_output["native"]["sequence"] == new_output["native"]["sequence"]

    def test_native_score_matches_exactly(
        self, original_output: dict, new_output: dict
    ) -> None:
        """Native score must match within tight tolerance."""
        old_score = original_output["native"]["score"]
        new_score = new_output["native"]["score"]
        assert abs(old_score - new_score) < 1e-4, (
            f"Native scores differ: original={old_score}, new={new_score}"
        )

    def test_native_metadata_matches(
        self, original_output: dict, new_output: dict
    ) -> None:
        """Native metadata (name, chains, model) must match."""
        assert original_output["native"]["name"] == new_output["native"]["name"]
        assert (
            original_output["native"]["fixed_chains"]
            == new_output["native"]["fixed_chains"]
        )
        assert (
            original_output["native"]["designed_chains"]
            == new_output["native"]["designed_chains"]
        )
        assert (
            original_output["native"]["model_name"]
            == new_output["native"]["model_name"]
        )

    def test_designed_sequences_match_exactly(
        self, original_output: dict, new_output: dict
    ) -> None:
        """Designed sequences must match exactly (same seed = deterministic)."""
        assert len(original_output["sequences"]) == len(new_output["sequences"])

        for i, (orig_seq, new_seq) in enumerate(
            zip(original_output["sequences"], new_output["sequences"])
        ):
            assert orig_seq["sequence"] == new_seq["sequence"], (
                f"Sequence {i} differs:\n"
                f"  Original: {orig_seq['sequence']}\n"
                f"  New: {new_seq['sequence']}"
            )

    def test_designed_scores_match(
        self, original_output: dict, new_output: dict
    ) -> None:
        """Designed scores must match within tolerance."""
        for i, (orig_seq, new_seq) in enumerate(
            zip(original_output["sequences"], new_output["sequences"])
        ):
            assert abs(orig_seq["score"] - new_seq["score"]) < 1e-4, (
                f"Score {i} differs: original={orig_seq['score']}, "
                f"new={new_seq['score']}"
            )

    def test_seq_recovery_matches(
        self, original_output: dict, new_output: dict
    ) -> None:
        """Sequence recovery must match within tolerance."""
        for i, (orig_seq, new_seq) in enumerate(
            zip(original_output["sequences"], new_output["sequences"])
        ):
            assert abs(orig_seq["seq_recovery"] - new_seq["seq_recovery"]) < 1e-4, (
                f"Seq recovery {i} differs: "
                f"original={orig_seq['seq_recovery']}, "
                f"new={new_seq['seq_recovery']}"
            )


@pytest.mark.skipif(not weights_available(), reason="Model weights not available")
class TestInferenceRegression:
    """Regression tests to ensure the new code produces consistent results.

    The fixture 6MRR_inference_old.json captures what the NEW code produces.
    These tests ensure we don't accidentally change the new code's behavior.
    """

    @pytest.fixture
    def expected_output(self) -> dict:
        """Load fixture generated from NEW code (for regression testing)."""
        fixture_path = FIXTURES_DIR / "6MRR_inference_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new InferenceRunner."""
        import torch

        pdb_path = DATA_DIR / "6MRR.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        runner = InferenceRunner(model_name="v_48_020", device=torch.device("cpu"))
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=3,
            seed=42,
        )
        return {
            "native": {
                "name": result.native.name,
                "score": result.native.score,
                "fixed_chains": result.native.fixed_chains,
                "designed_chains": result.native.designed_chains,
                "model_name": result.native.model_name,
                "sequence": result.native.sequence,
            },
            "sequences": [
                {
                    "temperature": s.temperature,
                    "sample_index": s.sample_index,
                    "score": s.score,
                    "seq_recovery": s.seq_recovery,
                    "sequence": s.sequence,
                }
                for s in result.sequences
            ],
        }

    def test_native_sequence_matches_exactly(
        self, expected_output: dict, new_output: dict
    ) -> None:
        """Native sequence must match exactly."""
        assert expected_output["native"]["sequence"] == new_output["native"]["sequence"]

    def test_native_score_matches(
        self, expected_output: dict, new_output: dict
    ) -> None:
        """Native score must match within tight tolerance."""
        old_score = expected_output["native"]["score"]
        new_score = new_output["native"]["score"]
        assert abs(old_score - new_score) < 1e-4, (
            f"Native scores differ: expected={old_score}, actual={new_score}"
        )

    def test_native_metadata_matches(
        self, expected_output: dict, new_output: dict
    ) -> None:
        """Native metadata (name, chains, model) must match."""
        assert expected_output["native"]["name"] == new_output["native"]["name"]
        assert (
            expected_output["native"]["fixed_chains"]
            == new_output["native"]["fixed_chains"]
        )
        assert (
            expected_output["native"]["designed_chains"]
            == new_output["native"]["designed_chains"]
        )
        assert (
            expected_output["native"]["model_name"]
            == new_output["native"]["model_name"]
        )

    def test_designed_sequences_match_exactly(
        self, expected_output: dict, new_output: dict
    ) -> None:
        """Designed sequences must match exactly (same seed = deterministic)."""
        assert len(expected_output["sequences"]) == len(new_output["sequences"])

        for i, (expected_seq, new_seq) in enumerate(
            zip(expected_output["sequences"], new_output["sequences"])
        ):
            assert expected_seq["sequence"] == new_seq["sequence"], (
                f"Sequence {i} differs:\n"
                f"  Expected: {expected_seq['sequence']}\n"
                f"  Actual: {new_seq['sequence']}"
            )

    def test_designed_scores_match(
        self, expected_output: dict, new_output: dict
    ) -> None:
        """Designed scores must match within tolerance."""
        for i, (expected_seq, new_seq) in enumerate(
            zip(expected_output["sequences"], new_output["sequences"])
        ):
            assert abs(expected_seq["score"] - new_seq["score"]) < 1e-4, (
                f"Score {i} differs: expected={expected_seq['score']}, "
                f"actual={new_seq['score']}"
            )

    def test_seq_recovery_matches(
        self, expected_output: dict, new_output: dict
    ) -> None:
        """Sequence recovery must match within tolerance."""
        for i, (expected_seq, new_seq) in enumerate(
            zip(expected_output["sequences"], new_output["sequences"])
        ):
            assert abs(expected_seq["seq_recovery"] - new_seq["seq_recovery"]) < 1e-4, (
                f"Seq recovery {i} differs: "
                f"expected={expected_seq['seq_recovery']}, "
                f"actual={new_seq['seq_recovery']}"
            )


@pytest.mark.skipif(not weights_available(), reason="Model weights not available")
class TestInferenceBackwardCompat:
    """Test backward compatibility of inference results."""

    @pytest.fixture
    def runner(self) -> InferenceRunner:
        """Create an InferenceRunner instance."""
        return InferenceRunner(model_name="v_48_020")

    @pytest.fixture
    def pdb_path(self):
        """Get path to test PDB file."""
        pdb = DATA_DIR / "6MRR.pdb"
        if not pdb.exists():
            pytest.skip(f"Test PDB not found: {pdb}")
        return pdb

    def test_native_sequence_matches_pdb(self, runner, pdb_path):
        """Verify native sequence matches the PDB file."""
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=1,
            seed=42,
        )

        # The native sequence should be the full 68 residues of chain A
        native_seq = result.native.sequence
        assert len(native_seq) == 68

        # Known first few residues of 6MRR chain A
        # (verified from PDB structure)
        assert native_seq.startswith("GWSTELE")

    def test_native_score_is_reasonable(self, runner, pdb_path):
        """Verify native score is within expected range."""
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=1,
            seed=42,
        )

        # Native score should be positive (negative log probability)
        assert result.native.score > 0
        # Score should be reasonable (typically 1-3 for well-folded proteins)
        assert result.native.score < 10

    def test_designed_sequences_have_correct_length(self, runner, pdb_path):
        """Verify designed sequences have correct length."""
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=3,
            seed=42,
        )

        for seq_result in result.sequences:
            assert len(seq_result.sequence) == 68

    def test_designed_scores_better_than_native(self, runner, pdb_path):
        """Designed sequences typically have better (lower) scores."""
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=5,
            seed=42,
        )

        # At least some designed sequences should score better than native
        best_designed = min(s.score for s in result.sequences)
        assert best_designed < result.native.score

    def test_fixed_positions_preserved(self, runner, pdb_path):
        """Verify fixed positions are not mutated."""
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A10-A20",  # Only design positions 10-20
            num_sequences=3,
            seed=42,
        )

        native_seq = result.native.sequence
        for seq_result in result.sequences:
            designed_seq = seq_result.sequence
            # Positions 1-9 should match native (0-indexed: 0-8)
            assert designed_seq[:9] == native_seq[:9], (
                f"Fixed region mismatch: {designed_seq[:9]} != {native_seq[:9]}"
            )
            # Positions 21-68 should match native (0-indexed: 20-67)
            assert designed_seq[20:] == native_seq[20:], (
                f"Fixed region mismatch: {designed_seq[20:]} != {native_seq[20:]}"
            )

    def test_seq_recovery_calculation(self, runner, pdb_path):
        """Verify sequence recovery is calculated correctly."""
        result = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A68",
            num_sequences=1,
            seed=42,
        )

        seq_result = result.sequences[0]
        native_seq = result.native.sequence
        designed_seq = seq_result.sequence

        # Calculate expected recovery
        matches = sum(1 for a, b in zip(native_seq, designed_seq) if a == b)
        expected_recovery = matches / len(native_seq)

        # Should match reported recovery (within floating point tolerance)
        assert abs(seq_result.seq_recovery - expected_recovery) < 0.01

    def test_deterministic_with_seed(self, runner, pdb_path):
        """Verify same seed produces same results."""
        result1 = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A20",
            num_sequences=2,
            seed=12345,
        )
        result2 = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A20",
            num_sequences=2,
            seed=12345,
        )

        # Sequences should match exactly
        for s1, s2 in zip(result1.sequences, result2.sequences):
            assert s1.sequence == s2.sequence
            assert abs(s1.score - s2.score) < 1e-6

    def test_temperature_affects_diversity(self, runner, pdb_path):
        """Higher temperature should produce more diverse sequences."""
        # Low temperature
        result_low = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A20",
            num_sequences=5,
            temperatures=[0.1],
            seed=42,
        )

        # High temperature
        result_high = runner.design_single(
            pdb_path=pdb_path,
            designable_res="A1-A20",
            num_sequences=5,
            temperatures=[1.0],
            seed=42,
        )

        # Calculate average pairwise differences
        def avg_diff(seqs):
            diffs = []
            for i, s1 in enumerate(seqs):
                for s2 in seqs[i + 1 :]:
                    diff = sum(1 for a, b in zip(s1, s2) if a != b)
                    diffs.append(diff)
            return sum(diffs) / len(diffs) if diffs else 0

        low_seqs = [s.sequence for s in result_low.sequences]
        high_seqs = [s.sequence for s in result_high.sequences]

        low_diversity = avg_diff(low_seqs)
        high_diversity = avg_diff(high_seqs)

        # High temperature should have more diversity
        assert high_diversity >= low_diversity


@pytest.mark.skipif(not weights_available(), reason="Model weights not available")
class TestSymmetricDesignBackwardCompat:
    """Test backward compatibility for symmetric design."""

    @pytest.fixture
    def runner(self) -> InferenceRunner:
        """Create an InferenceRunner instance."""
        return InferenceRunner(model_name="v_48_020")

    @pytest.fixture
    def homooligomer_pdb(self):
        """Get path to homooligomer test PDB."""
        pdb = EXAMPLES_DIR / "complex" / "homooligomer" / "4GYT.pdb"
        if not pdb.exists():
            pytest.skip(f"Homooligomer PDB not found: {pdb}")
        return pdb

    def test_symmetric_positions_match(self, runner, homooligomer_pdb):
        """Verify symmetric positions have the same amino acid."""
        result = runner.design_single(
            pdb_path=homooligomer_pdb,
            designable_res="A7-A15,B7-B15",
            symmetric_res="A7-A15:B7-B15",
            num_sequences=3,
            seed=42,
        )

        for seq_result in result.sequences:
            # Sequence has chains separated by /
            chains = seq_result.sequence.split("/")
            if len(chains) >= 2:
                chain_a = chains[0]
                chain_b = chains[1]
                # The designed regions (positions 7-15, 0-indexed: 6-14)
                # should match between chains
                assert chain_a[6:15] == chain_b[6:15], (
                    f"Symmetric regions don't match: {chain_a[6:15]} != {chain_b[6:15]}"
                )
