"""Tests comparing compute_probs against original protein_mpnn_run.py implementation.

This test ensures that the new compute_probs implementation produces identical
results to the original run/protein_mpnn/protein_mpnn_run.py script.

There are two types of tests:
1. TestProbsMatchesOriginal - Compares new code against fixtures generated from
   the ORIGINAL code in run/ using scripts/generate_original_fixtures.py
2. TestProbsRegression - Ensures the new code is deterministic and behaves correctly
"""

from __future__ import annotations

import json

import numpy as np
import pytest
import torch

from proteinmpnn.inference import InferenceRunner
from proteinmpnn.utils.constants import ROOT_DIR, WEIGHTS_PATH

# Test data paths
DATA_DIR = ROOT_DIR / "data" / "pdbs"
FIXTURES_DIR = ROOT_DIR / "tests" / "fixtures"


def weights_available() -> bool:
    """Check if model weights are available."""
    return (WEIGHTS_PATH / "v_48_020.pt").exists()


@pytest.mark.skipif(not weights_available(), reason="Model weights not available")
class TestProbsMatchesOriginal:
    """Tests comparing compute_probs to fixtures from ORIGINAL code.

    The fixtures were generated by running the original code in run/ directory
    using scripts/generate_original_fixtures.py. This ensures we compare against
    the true original behavior, not against outputs generated by the new code.
    """

    @pytest.fixture
    def runner(self) -> InferenceRunner:
        """Create an InferenceRunner instance on CPU."""
        return InferenceRunner(model_name="v_48_020", device=torch.device("cpu"))

    @pytest.fixture
    def pdb_path(self):
        """Get path to test PDB file."""
        pdb = DATA_DIR / "6MRR.pdb"
        if not pdb.exists():
            pytest.skip(f"Test PDB not found: {pdb}")
        return pdb

    def test_unconditional_probs_match_original(self, runner, pdb_path):
        """Test that unconditional probs match original implementation."""
        # Load fixture from original code
        npz_path = FIXTURES_DIR / "6MRR_unconditional_probs_original.npz"
        json_path = FIXTURES_DIR / "6MRR_unconditional_probs_original.json"

        if not npz_path.exists() or not json_path.exists():
            pytest.skip("Fixture not found - run scripts/generate_original_fixtures.py")

        with np.load(npz_path) as data:
            orig_log_probs = data["log_probs"]

        with json_path.open() as f:
            metadata = json.load(f)

        # Run new implementation with same seed
        result = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=True,
            seed=metadata["seed"],
        )

        # Compare
        np.testing.assert_array_almost_equal(
            result.log_probs,
            orig_log_probs,
            decimal=5,
            err_msg="Unconditional probs don't match original implementation",
        )

    def test_conditional_probs_all_designable_match_original(self, runner, pdb_path):
        """Test conditional probs match original when all residues are designable."""
        # Load fixture from original code
        npz_path = FIXTURES_DIR / "6MRR_conditional_probs_all_original.npz"
        json_path = FIXTURES_DIR / "6MRR_conditional_probs_all_original.json"

        if not npz_path.exists() or not json_path.exists():
            pytest.skip("Fixture not found - run scripts/generate_original_fixtures.py")

        with np.load(npz_path) as data:
            orig_log_probs = data["log_probs"]

        with json_path.open() as f:
            metadata = json.load(f)

        # Run new implementation with same seed
        result = runner.compute_probs(
            pdb_path=pdb_path,
            designable_res="",  # All residues
            unconditional=False,
            seed=metadata["seed"],
        )

        # Compare
        np.testing.assert_array_almost_equal(
            result.log_probs,
            orig_log_probs,
            decimal=5,
            err_msg="Conditional probs (all designable) don't match original",
        )

    def test_conditional_probs_with_fixed_positions_match_original(
        self, runner, pdb_path
    ):
        """Test conditional probs match original with fixed positions."""
        # Load fixture from original code
        npz_path = FIXTURES_DIR / "6MRR_conditional_probs_A1-A30_original.npz"
        json_path = FIXTURES_DIR / "6MRR_conditional_probs_A1-A30_original.json"

        if not npz_path.exists() or not json_path.exists():
            pytest.skip("Fixture not found - run scripts/generate_original_fixtures.py")

        with np.load(npz_path) as data:
            orig_log_probs = data["log_probs"]

        with json_path.open() as f:
            metadata = json.load(f)

        # Run new implementation with same seed and designable_res
        result = runner.compute_probs(
            pdb_path=pdb_path,
            designable_res=metadata["designable_res"],
            unconditional=False,
            seed=metadata["seed"],
        )

        # Compare
        np.testing.assert_array_almost_equal(
            result.log_probs,
            orig_log_probs,
            decimal=5,
            err_msg="Conditional probs (A1-A30 designable) don't match original",
        )

    def test_residue_count_matches_original(self, runner, pdb_path):
        """Test that residue count matches original."""
        json_path = FIXTURES_DIR / "6MRR_unconditional_probs_original.json"
        if not json_path.exists():
            pytest.skip("Fixture not found - run scripts/generate_original_fixtures.py")

        with json_path.open() as f:
            metadata = json.load(f)

        result = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=True,
            seed=42,
        )

        assert len(result.residue_info) == metadata["num_residues"]
        assert result.log_probs.shape[0] == metadata["num_residues"]


@pytest.mark.skipif(not weights_available(), reason="Model weights not available")
class TestProbsRegression:
    """Regression tests to ensure compute_probs produces consistent results."""

    @pytest.fixture
    def runner(self) -> InferenceRunner:
        """Create an InferenceRunner instance."""
        return InferenceRunner(model_name="v_48_020")

    @pytest.fixture
    def pdb_path(self):
        """Get path to test PDB file."""
        pdb = DATA_DIR / "6MRR.pdb"
        if not pdb.exists():
            pytest.skip(f"Test PDB not found: {pdb}")
        return pdb

    def test_log_probs_shape_correct(self, runner, pdb_path):
        """Test that log_probs shape is correct."""
        result = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=True,
            seed=42,
        )

        # Should have 21 amino acid columns
        assert result.log_probs.shape[1] == 21

    def test_deterministic_with_same_seed(self, runner, pdb_path):
        """Test that results are deterministic with same seed."""
        result1 = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=False,
            seed=12345,
        )
        result2 = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=False,
            seed=12345,
        )

        np.testing.assert_array_equal(
            result1.log_probs,
            result2.log_probs,
            err_msg="Results not deterministic with same seed",
        )

    def test_different_seeds_produce_different_conditional_results(
        self, runner, pdb_path
    ):
        """Test that different seeds produce different conditional results."""
        result1 = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=False,
            seed=42,
        )
        result2 = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=False,
            seed=123,
        )

        # Conditional probs depend on randn, so should differ with different seeds
        assert not np.allclose(result1.log_probs, result2.log_probs)

    def test_unconditional_same_regardless_of_seed(self, runner, pdb_path):
        """Test that unconditional probs are the same regardless of seed.

        Unconditional probs don't use random noise, so should be deterministic.
        """
        result1 = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=True,
            seed=42,
        )
        result2 = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=True,
            seed=123,
        )

        np.testing.assert_array_almost_equal(
            result1.log_probs,
            result2.log_probs,
            decimal=5,
            err_msg="Unconditional probs should be same regardless of seed",
        )

    def test_residue_info_has_correct_structure(self, runner, pdb_path):
        """Test that residue_info has correct structure."""
        result = runner.compute_probs(
            pdb_path=pdb_path,
            unconditional=True,
            seed=42,
        )

        assert len(result.residue_info) > 0

        # Check first residue has expected fields
        first_residue = result.residue_info[0]
        assert first_residue.chain == "A"
        assert first_residue.residue_idx == 1
