"""Tests for backward compatibility with old generate_json.py output.

These tests verify that the new SingleStateDesignInput and MultiStateDesignInput
classes produce output equivalent to the old ProteinDesignInputFormatter from
run/generate_json.py.

Note: The old code has a bug where unknown residue types (like water/HOH) are
mapped to 'XXX' (3 characters) instead of 'X' (1 character), causing sequence
lengths to differ. The new code fixes this bug. These tests verify that the
critical fields (designable, symmetric) match exactly, while accounting for
the sequence length difference.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

import pytest

from proteinmpnn.data.multi_state import MultiStateDesignInput
from proteinmpnn.data.single_state import SingleStateDesignInput
from proteinmpnn.utils.constants import ROOT_DIR

if TYPE_CHECKING:
    from pathlib import Path

# Paths relative to repo root
FIXTURES_DIR = ROOT_DIR / "tests" / "fixtures"
DATA_DIR = ROOT_DIR / "data" / "pdbs"
EXAMPLES_DIR = ROOT_DIR / "examples"


class TestSingleStateBackwardCompat:
    """Test backward compatibility for single-state design."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "6MRR_A1-A68_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_path = DATA_DIR / "6MRR.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A1-A68",
        )
        config = design.to_config()
        return json.loads(config.model_dump_json())

    def test_designable_residues_match_exactly(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify designable residues match exactly between old and new code."""
        assert len(old_output["designable"]) == len(new_output["designable"])

        for old_res, new_res in zip(old_output["designable"], new_output["designable"]):
            assert old_res["chain"] == new_res["chain"]
            assert old_res["resid"] == new_res["resid"]
            assert old_res["WTAA"] == new_res["WTAA"]
            assert old_res["MutTo"] == new_res["MutTo"]

    def test_symmetric_groups_match(self, old_output: dict, new_output: dict) -> None:
        """Verify symmetric groups match between old and new code."""
        assert old_output["symmetric"] == new_output["symmetric"]

    def test_amino_acid_portion_matches(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify the amino acid (non-X) portion of sequences match.

        Both old and new code should produce the same amino acids for real
        residues. The difference is only in how gaps/unknown residues are
        represented.
        """
        for chain_id in old_output["sequence"]:
            old_seq = old_output["sequence"][chain_id]
            new_seq = new_output["sequence"][chain_id]

            # Extract non-X characters (real amino acids)
            old_aas = "".join(c for c in old_seq if c != "X")
            new_aas = "".join(c for c in new_seq if c != "X")

            assert old_aas == new_aas, (
                f"Chain {chain_id} amino acids differ:\nOld: {old_aas}\nNew: {new_aas}"
            )

    def test_old_sequence_is_longer_due_to_xxx_bug(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Document the XXX bug causes longer sequences in old code.

        The old code has a bug where unknown residues (like HOH/water) are
        encoded as 'XXX' (3 chars) instead of 'X' (1 char). This causes the
        old sequence to be longer than the new one.
        """
        old_seq = old_output["sequence"]["A"]
        new_seq = new_output["sequence"]["A"]

        # Old sequence should be longer due to the bug
        assert len(old_seq) > len(new_seq), (
            f"Expected old sequence ({len(old_seq)}) to be longer than "
            f"new sequence ({len(new_seq)}) due to XXX bug"
        )

        # Old code: each water adds 3 X's, new code: each water adds 1 X
        # Plus both have the same gaps (32 in this case)
        # So: old_x_count = 3 * waters + gaps, new_x_count = waters + gaps
        # Difference in length = 2 * waters
        length_diff = len(old_seq) - len(new_seq)
        assert length_diff > 0, "Old sequence should be longer"

    def test_new_sequence_length_is_correct(self, new_output: dict) -> None:
        """Verify new sequence length matches expected PDB structure.

        For 6MRR, residues are numbered 1-216, so sequence should be 216 chars.
        """
        new_seq = new_output["sequence"]["A"]
        # PDB has residue numbers 1-216
        assert len(new_seq) == 216, f"Expected sequence length 216, got {len(new_seq)}"

    def test_chain_ids_match(self, old_output: dict, new_output: dict) -> None:
        """Verify the same chains are present in both outputs."""
        assert set(old_output["sequence"].keys()) == set(new_output["sequence"].keys())


class TestDesignableResiduesAreComplete:
    """Test that all designable residues are properly captured."""

    @pytest.fixture
    def pdb_path(self) -> Path:
        """Return path to test PDB."""
        path = DATA_DIR / "6MRR.pdb"
        if not path.exists():
            pytest.skip(f"PDB not found: {path}")
        return path

    def test_designable_count_matches_range(self, pdb_path: Path) -> None:
        """Verify designable residue count matches the specified range."""
        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A1-A68",
        )
        config = design.to_config()
        assert len(config.designable) == 68

    def test_designable_residue_numbers_are_sequential(self, pdb_path: Path) -> None:
        """Verify designable residue numbers are 1-68."""
        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A1-A68",
        )
        config = design.to_config()

        resids = [r.resid for r in config.designable]
        assert resids == list(range(1, 69))

    def test_all_designable_are_real_amino_acids(self, pdb_path: Path) -> None:
        """Verify no designable residue is a gap (X)."""
        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A1-A68",
        )
        config = design.to_config()

        for res in config.designable:
            assert res.WTAA != "X", f"Residue {res.resid} should not be a gap"


class TestJsonOutputFormat:
    """Test that JSON output format is correct."""

    @pytest.fixture
    def config_dict(self) -> dict:
        """Generate config as dict."""
        pdb_path = DATA_DIR / "6MRR.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A10-A20",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_has_required_keys(self, config_dict: dict) -> None:
        """Verify JSON has all required top-level keys."""
        required_keys = {"sequence", "designable", "symmetric"}
        assert required_keys <= set(config_dict.keys())

    def test_sequence_is_dict_of_strings(self, config_dict: dict) -> None:
        """Verify sequence field structure."""
        assert isinstance(config_dict["sequence"], dict)
        for chain_id, seq in config_dict["sequence"].items():
            assert isinstance(chain_id, str)
            assert isinstance(seq, str)

    def test_designable_is_list_of_dicts(self, config_dict: dict) -> None:
        """Verify designable field structure."""
        assert isinstance(config_dict["designable"], list)
        for res in config_dict["designable"]:
            assert isinstance(res, dict)
            assert "chain" in res
            assert "resid" in res
            assert "WTAA" in res
            assert "MutTo" in res

    def test_symmetric_is_list_of_lists(self, config_dict: dict) -> None:
        """Verify symmetric field structure."""
        assert isinstance(config_dict["symmetric"], list)
        for group in config_dict["symmetric"]:
            assert isinstance(group, list)


# =============================================================================
# Helper functions for comparing old and new output
# =============================================================================


def compare_designable_residues(old_output: dict, new_output: dict) -> None:
    """Compare designable residues between old and new output.

    Filters out residues with WTAA='XXX' from old output (the old XXX bug).
    Sorts by (chain, resid) before comparing to handle different ordering.
    """
    old_designable = [r for r in old_output["designable"] if r["WTAA"] != "XXX"]
    new_designable = new_output["designable"]

    # fmt: off
    assert len(old_designable) == len(new_designable), (
        f"Designable count mismatch: old={len(old_designable)}, new={len(new_designable)}" # noqa: E501
    )
    # fmt: on

    # Sort both lists by (chain, resid) for comparison
    old_sorted = sorted(old_designable, key=lambda r: (r["chain"], r["resid"]))
    new_sorted = sorted(new_designable, key=lambda r: (r["chain"], r["resid"]))

    for old_res, new_res in zip(old_sorted, new_sorted):
        assert old_res["chain"] == new_res["chain"], (
            f"Chain mismatch: old={old_res['chain']}, new={new_res['chain']}"
        )
        assert old_res["resid"] == new_res["resid"], (
            f"Resid mismatch: old={old_res['resid']}, new={new_res['resid']}"
        )
        assert old_res["WTAA"] == new_res["WTAA"], (
            f"WTAA mismatch at {old_res['chain']}{old_res['resid']}: "
            f"old={old_res['WTAA']}, new={new_res['WTAA']}"
        )
        assert old_res["MutTo"] == new_res["MutTo"], (
            f"MutTo mismatch at {old_res['chain']}{old_res['resid']}: "
            f"old={old_res['MutTo']}, new={new_res['MutTo']}"
        )


def compare_sequences(old_output: dict, new_output: dict) -> None:
    """Compare amino acid sequences (excluding X characters)."""
    assert set(old_output["sequence"].keys()) == set(new_output["sequence"].keys())

    for chain_id in old_output["sequence"]:
        old_seq = old_output["sequence"][chain_id]
        new_seq = new_output["sequence"][chain_id]

        old_aas = "".join(c for c in old_seq if c != "X")
        new_aas = "".join(c for c in new_seq if c != "X")

        assert old_aas == new_aas, (
            f"Chain {chain_id} amino acids differ:\nOld: {old_aas}\nNew: {new_aas}"
        )


# =============================================================================
# Single-state backward compatibility tests for other examples
# =============================================================================


class TestHeterooligomerBackwardCompat:
    """Test backward compatibility for complex/heterooligomer example (3HTN)."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "3HTN_heterooligomer_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_path = EXAMPLES_DIR / "complex" / "heterooligomer" / "3HTN.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A43-A185,B43-B185,C43-C185",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_residues_match(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify designable residues match (excluding XXX bug residues)."""
        compare_designable_residues(old_output, new_output)

    def test_sequences_match(self, old_output: dict, new_output: dict) -> None:
        """Verify amino acid sequences match."""
        compare_sequences(old_output, new_output)

    def test_chain_ids_match(self, old_output: dict, new_output: dict) -> None:
        """Verify the same chains are present."""
        assert set(old_output["sequence"].keys()) == set(new_output["sequence"].keys())

    def test_symmetric_groups_match(self, old_output: dict, new_output: dict) -> None:
        """Verify symmetric groups match (should be empty for heterooligomer)."""
        assert old_output["symmetric"] == new_output["symmetric"]


class TestHomooligomerBackwardCompat:
    """Test backward compatibility for complex/homooligomer example (4GYT)."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "4GYT_homooligomer_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_path = EXAMPLES_DIR / "complex" / "homooligomer" / "4GYT.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A7-A183,B7-B183",
            symmetric_res="A7-A183:B7-B183",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_residues_match(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify designable residues match."""
        compare_designable_residues(old_output, new_output)

    def test_sequences_match(self, old_output: dict, new_output: dict) -> None:
        """Verify amino acid sequences match."""
        compare_sequences(old_output, new_output)

    def test_symmetric_groups_match(self, old_output: dict, new_output: dict) -> None:
        """Verify symmetric groups match."""
        assert old_output["symmetric"] == new_output["symmetric"]

    def test_symmetric_groups_not_empty(self, new_output: dict) -> None:
        """Verify homooligomer has symmetric constraints."""
        assert len(new_output["symmetric"]) > 0


class TestDestabilizeBackwardCompat:
    """Test backward compatibility for monomer/destabilize example."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "6MRR_destabilize_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_path = EXAMPLES_DIR / "monomer" / "destabilize" / "6MRR.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A1,A43",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_residues_match(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify designable residues match."""
        compare_designable_residues(old_output, new_output)

    def test_designable_count_is_two(self, new_output: dict) -> None:
        """Verify only 2 residues are designable (A1 and A43)."""
        assert len(new_output["designable"]) == 2


class TestMutationClusterBackwardCompat:
    """Test backward compatibility for monomer/mutation_cluster example."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "6MRR_mutation_cluster_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_path = EXAMPLES_DIR / "monomer" / "mutation_cluster" / "6MRR.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            cluster_center="A1,A43",
            cluster_radius=10.0,
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_residues_match(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify designable residues match."""
        compare_designable_residues(old_output, new_output)

    def test_cluster_finds_multiple_residues(self, new_output: dict) -> None:
        """Verify cluster-based selection finds multiple residues."""
        # A cluster with 10A radius should find more than just the center residues
        assert len(new_output["designable"]) > 2


class TestMutationPairsBackwardCompat:
    """Test backward compatibility for other/mutation_pairs example."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "3HTN_mutation_pairs_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_path = EXAMPLES_DIR / "other" / "mutation_pairs" / "3HTN.pdb"
        if not pdb_path.exists():
            pytest.skip(f"PDB not found: {pdb_path}")

        design = SingleStateDesignInput(
            pdb_path=pdb_path,
            designable_res="A53,A114-A116,A141,B104,B118,B120,B131-B135,B145",
            default_design_setting="all-C",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_residues_match(
        self, old_output: dict, new_output: dict
    ) -> None:
        """Verify designable residues match."""
        compare_designable_residues(old_output, new_output)

    def test_design_setting_is_all_minus_c(self, new_output: dict) -> None:
        """Verify all designable residues have 'all-C' as MutTo."""
        for res in new_output["designable"]:
            assert res["MutTo"] == "all-C"


# =============================================================================
# Multi-state backward compatibility tests
# =============================================================================


class TestSingleConstraintMSDBackwardCompat:
    """Test backward compatibility for multi_state/single_constraint example.

    Note: This test may be skipped due to a Biopython bug with certain PDB files
    that have malformed REMARK 350 headers.
    """

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "4GYT_single_constraint_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_dir = EXAMPLES_DIR / "multi_state" / "single_constraint"
        if not pdb_dir.exists():
            pytest.skip(f"Directory not found: {pdb_dir}")

        try:
            design = MultiStateDesignInput(
                pdb_dir=pdb_dir,
                designable_res="4GYT_dimer:A7-A183,B7-B183;4GYT_monomer:A7-A183",
                constraints="4GYT_dimer:A7-A183:0.5,4GYT_dimer:B7-B183:0.5,4GYT_monomer:A7-A183:1",
            )
            return json.loads(design.to_config().model_dump_json())
        except UnboundLocalError:
            # Biopython bug with certain PDB files
            pytest.skip("Biopython parser bug with this PDB file")

    def test_designable_count_matches(self, old_output: dict, new_output: dict) -> None:
        """Verify designable residue counts match."""
        old_count = len([r for r in old_output["designable"] if r["WTAA"] != "XXX"])
        new_count = len(new_output["designable"])
        assert old_count == new_count

    def test_has_tied_betas(self, new_output: dict) -> None:
        """Verify multi-state output has tied_betas field."""
        assert "tied_betas" in new_output

    def test_has_chain_key(self, new_output: dict) -> None:
        """Verify multi-state output has chain_key field."""
        assert "chain_key" in new_output


class TestMixedDesignMSDBackwardCompat:
    """Test backward compatibility for multi_state/mixed_design example."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "12E8_mixed_design_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_dir = EXAMPLES_DIR / "multi_state" / "mixed_design"
        if not pdb_dir.exists():
            pytest.skip(f"Directory not found: {pdb_dir}")

        design = MultiStateDesignInput(
            pdb_dir=pdb_dir,
            designable_res="12E8:L1-L214,H1-H221;12E8_chainL_monomer:L1-L214",
            constraints="12E8:L1-L214:1,12E8_chainL_monomer:L1-L214:-2",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_count_matches(self, old_output: dict, new_output: dict) -> None:
        """Verify designable residue counts match."""
        old_count = len([r for r in old_output["designable"] if r["WTAA"] != "XXX"])
        new_count = len(new_output["designable"])
        assert old_count == new_count

    def test_has_negative_beta(self, new_output: dict) -> None:
        """Verify mixed design has negative beta weight for disfavored state."""
        tied_betas = new_output.get("tied_betas", {})
        has_negative = any(v < 0 for v in tied_betas.values())
        assert has_negative, (
            "Mixed design should have negative beta for disfavored state"
        )


class TestMultipleConstraintMSDBackwardCompat:
    """Test backward compatibility for multi_state/multiple_constraint example."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "1a0o_multiple_constraint_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_dir = EXAMPLES_DIR / "multi_state" / "multiple_constraint"
        if not pdb_dir.exists():
            pytest.skip(f"Directory not found: {pdb_dir}")

        design = MultiStateDesignInput(
            pdb_dir=pdb_dir,
            designable_res="1a0o:A1-A128,B1-B70;1a0o_chainA_monomer:A1-A128;1a0o_chainB_monomer:B1-B70",
            constraints="1a0o:A1-A128:1,1a0o_chainA_monomer:A1-A128:1;1a0o:B1-B70:1,1a0o_chainB_monomer:B1-B70:-1",
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_count_matches(self, old_output: dict, new_output: dict) -> None:
        """Verify designable residue counts match."""
        old_count = len([r for r in old_output["designable"] if r["WTAA"] != "XXX"])
        new_count = len(new_output["designable"])
        assert old_count == new_count

    def test_multiple_chains_in_output(self, new_output: dict) -> None:
        """Verify output contains multiple chains from combined structure."""
        assert len(new_output["sequence"]) >= 3  # At least 3 chains from 3 PDBs


class TestBidirectionalMSDBackwardCompat:
    """Test backward compatibility for multi_state/bidirectional example."""

    @pytest.fixture
    def old_output(self) -> dict:
        """Load the fixture generated by old code."""
        fixture_path = FIXTURES_DIR / "scaffold_bidirectional_old.json"
        if not fixture_path.exists():
            pytest.skip(f"Fixture not found: {fixture_path}")
        with fixture_path.open() as f:
            return json.load(f)

    @pytest.fixture
    def new_output(self) -> dict:
        """Generate output using new code."""
        pdb_dir = EXAMPLES_DIR / "multi_state" / "bidirectional"
        if not pdb_dir.exists():
            pytest.skip(f"Directory not found: {pdb_dir}")

        design = MultiStateDesignInput(
            pdb_dir=pdb_dir,
            designable_res="scaffold_14:B1-B60;scaffold_21:B1-B60",
            constraints="scaffold_14:B1-B60:1,scaffold_21:B1-B60:1",
            bidirectional=True,
        )
        return json.loads(design.to_config().model_dump_json())

    def test_designable_count_matches(self, old_output: dict, new_output: dict) -> None:
        """Verify designable residue counts match."""
        old_count = len([r for r in old_output["designable"] if r["WTAA"] != "XXX"])
        new_count = len(new_output["designable"])
        assert old_count == new_count

    def test_symmetric_groups_present(self, new_output: dict) -> None:
        """Verify bidirectional design has symmetric groups."""
        assert len(new_output["symmetric"]) > 0
