#!/usr/bin/env python
"""Generate test fixtures using the ORIGINAL ProteinMPNN code in run/.

This script imports and runs the original implementation to create ground-truth
fixtures that the new code can be tested against. This ensures backward
compatibility by comparing against the actual original behavior, not against
outputs generated by the new code.

Usage:
    python scripts/generate_original_fixtures.py

The script will generate:
    tests/fixtures/6MRR_inference_original.json
"""

from __future__ import annotations

import copy
import json
import os
import sys
from pathlib import Path

# Add the run/ directory to sys.path so we can import from it
ROOT_DIR = Path(__file__).parent.parent
RUN_DIR = ROOT_DIR / "run"
sys.path.insert(0, str(RUN_DIR))

import numpy as np
import torch

# Now import from the original code
from mpnn_utils import (
    MODEL_CONFIG,
    determine_weight_directory,
    get_pdb_dataset,
    transform_inputs,
)
from protein_mpnn.protein_mpnn_utils import (
    ProteinMPNN,
    _S_to_seq,
    _scores,
    tied_featurize,
)


def parse_designable_res(
    designable_res: str, chain_sequences: dict[str, str]
) -> list[dict]:
    """Parse designable residue string like 'A1-A68' into list of residue specs.

    Args:
        designable_res: String like "A1-A68" or "A1-A10,A20-A30"
        chain_sequences: Dict mapping chain ID to sequence

    Returns:
        List of dicts with chain, resid, WTAA, MutTo keys
    """
    designable = []
    items = designable_res.split(",")

    for item in items:
        item = item.strip()
        if "-" in item:
            # Range like A1-A68
            parts = item.split("-")
            start_chain = parts[0][0]
            start_idx = int(parts[0][1:])
            end_chain = parts[1][0]
            end_idx = int(parts[1][1:])

            if start_chain != end_chain:
                raise ValueError(f"Range cannot span chains: {item}")

            chain = start_chain
            seq = chain_sequences.get(chain, "")

            for resid in range(start_idx, end_idx + 1):
                # Get the amino acid at this position (1-indexed)
                if resid <= len(seq):
                    wtaa = seq[resid - 1]
                else:
                    wtaa = "X"

                designable.append(
                    {
                        "chain": chain,
                        "resid": resid,
                        "WTAA": wtaa,
                        "MutTo": "all",
                    }
                )
        else:
            # Single residue like A1
            chain = item[0]
            resid = int(item[1:])
            seq = chain_sequences.get(chain, "")

            if resid <= len(seq):
                wtaa = seq[resid - 1]
            else:
                wtaa = "X"

            designable.append(
                {
                    "chain": chain,
                    "resid": resid,
                    "WTAA": wtaa,
                    "MutTo": "all",
                }
            )

    return designable


def generate_inference_fixture(
    pdb_path: Path,
    designable_res: str,
    model_name: str = "v_48_020",
    num_sequences: int = 3,
    temperature: float = 0.1,
    seed: int = 42,
) -> dict:
    """Generate inference output using the original ProteinMPNN code.

    Args:
        pdb_path: Path to the PDB file
        designable_res: Designable residue specification (e.g., "A1-A68")
        model_name: Name of the model to use
        num_sequences: Number of sequences to generate
        temperature: Sampling temperature
        seed: Random seed for reproducibility

    Returns:
        Dictionary containing inference results in fixture format
    """
    # Force CPU for cross-platform reproducibility
    device = torch.device("cpu")

    # Set seeds for reproducibility
    torch.manual_seed(seed)
    np.random.seed(seed)

    # Model hyperparameters
    hidden_dim = MODEL_CONFIG["hidden_dim"]
    num_layers = MODEL_CONFIG["num_layers"]

    # Load model weights
    model_weight_dir = determine_weight_directory()
    ckpt_path = os.path.join(model_weight_dir, f"{model_name}.pt")
    if not os.path.isfile(ckpt_path):
        raise ValueError(f"Model weights not found: {ckpt_path}")

    ckpt = torch.load(ckpt_path, map_location=device)
    num_edges = ckpt["num_edges"]

    # Build model
    model = ProteinMPNN(
        num_letters=21,
        node_features=hidden_dim,
        edge_features=hidden_dim,
        hidden_dim=hidden_dim,
        num_encoder_layers=num_layers,
        num_decoder_layers=num_layers,
        augment_eps=0.0,  # No backbone noise
        k_neighbors=num_edges,
    )
    model.to(device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    # Create a temporary directory with the PDB for get_pdb_dataset
    pdb_dir = pdb_path.parent
    pdb_name = pdb_path.stem

    # Parse the PDB
    pdb_ds = get_pdb_dataset(str(pdb_dir))

    # Find the correct protein (in case there are multiple)
    protein = None
    for p in pdb_ds:
        if p["name"] == pdb_name:
            protein = p
            break
    if protein is None:
        protein = pdb_ds[0]

    # Extract chain sequences from protein dict
    chain_sequences = {}
    for key in protein:
        if key.startswith("seq_chain_"):
            chain_id = key[-1]
            chain_sequences[chain_id] = protein[key]

    # Build design specs dict
    design_specs_dict = {
        "sequence": chain_sequences,
        "designable": parse_designable_res(designable_res, chain_sequences),
        "symmetric": [],
    }

    # Alphabet for amino acids
    alphabet = "ACDEFGHIKLMNPQRSTVWYX"
    omit_AAs_np = np.zeros(len(alphabet), dtype=np.float32)
    bias_AAs_np = np.zeros(len(alphabet), dtype=np.float32)

    BATCH_COPIES = 1
    batch_clones = [copy.deepcopy(protein) for _ in range(BATCH_COPIES)]

    # Transform inputs
    (
        chain_id_dict,
        fixed_positions_dict,
        pssm_dict,
        omit_AA_dict,
        bias_AA_dict_decoy,
        tied_positions_dict,
        bias_by_res_decoy,
    ) = transform_inputs(design_specs_dict, protein, experimental=False)

    # Featurize
    (
        X,
        S,
        mask,
        _,
        chain_M,
        chain_encoding_all,
        _,
        visible_list_list,
        masked_list_list,
        masked_chain_length_list_list,
        chain_M_pos,
        omit_AA_mask,
        residue_idx,
        _,
        tied_pos_list_of_lists_list,
        pssm_coef,
        pssm_bias,
        pssm_log_odds_all,
        bias_by_res_all,
        tied_beta,
    ) = tied_featurize(
        batch_clones,
        device,
        chain_id_dict,
        fixed_positions_dict,
        omit_AA_dict,
        tied_positions_dict,
        pssm_dict,
        None,  # bias_by_res_dict
    )

    # Compute native score
    # Reset seed right before generating randn_1 to match the new code's behavior
    torch.manual_seed(seed)
    with torch.no_grad():
        randn_1 = torch.randn(chain_M.shape, device=device)
        log_probs = model(
            X,
            S,
            mask,
            chain_M * chain_M_pos,
            residue_idx,
            chain_encoding_all,
            randn_1,
        )
        mask_for_loss = mask * chain_M * chain_M_pos
        native_scores, _ = _scores(S, log_probs, mask_for_loss)
        native_score = float(native_scores.cpu().numpy().mean())

    # Get native sequence
    native_seq = _S_to_seq(S[0], chain_M[0])

    # Get chain info
    sorted_masked_chain_letters = np.argsort(masked_list_list[0])
    print_masked_chains = [masked_list_list[0][i] for i in sorted_masked_chain_letters]
    sorted_visible_chain_letters = np.argsort(visible_list_list[0])
    print_visible_chains = [
        visible_list_list[0][i] for i in sorted_visible_chain_letters
    ]

    # Format the native sequence with chain separators
    masked_chain_length_list = masked_chain_length_list_list[0]
    masked_list = masked_list_list[0]
    start = 0
    list_of_AAs = []
    for mask_l in masked_chain_length_list:
        end = start + mask_l
        list_of_AAs.append(native_seq[start:end])
        start = end
    native_seq_formatted = "".join(list(np.array(list_of_AAs)[np.argsort(masked_list)]))

    # Add chain separators
    l0 = 0
    for mc_length in list(np.array(masked_chain_length_list)[np.argsort(masked_list)])[
        :-1
    ]:
        l0 += mc_length
        native_seq_formatted = (
            native_seq_formatted[:l0] + "/" + native_seq_formatted[l0:]
        )
        l0 += 1

    # Build result
    result = {
        "description": f"Inference output for {pdb_name} {designable_res} "
        f"with seed={seed}, "
        f"generated by ORIGINAL run_protein_mpnn.py code. CPU-only "
        "for reproducibility.",
        "seed": seed,
        "model_name": model_name,
        "designable_res": designable_res,
        "native": {
            "name": pdb_name,
            "score": native_score,
            "fixed_chains": print_visible_chains,
            "designed_chains": print_masked_chains,
            "model_name": model_name,
            "sequence": native_seq_formatted,
        },
        "sequences": [],
    }

    # Generate designed sequences
    with torch.no_grad():
        for i in range(num_sequences):
            randn_2 = torch.randn(chain_M.shape, device=device)

            if tied_positions_dict is None:
                sample_dict = model.sample(
                    X,
                    randn_2,
                    S,
                    chain_M,
                    chain_encoding_all,
                    residue_idx,
                    mask=mask,
                    temperature=temperature,
                    omit_AAs_np=omit_AAs_np,
                    bias_AAs_np=bias_AAs_np,
                    chain_M_pos=chain_M_pos,
                    omit_AA_mask=omit_AA_mask,
                    pssm_coef=pssm_coef,
                    pssm_bias=pssm_bias,
                    pssm_multi=0.0,
                    pssm_log_odds_flag=False,
                    pssm_log_odds_mask=(pssm_log_odds_all > 0.0).float(),
                    pssm_bias_flag=False,
                    bias_by_res=bias_by_res_all,
                )
            else:
                sample_dict = model.tied_sample(
                    X,
                    randn_2,
                    S,
                    chain_M,
                    chain_encoding_all,
                    residue_idx,
                    mask=mask,
                    temperature=temperature,
                    omit_AAs_np=omit_AAs_np,
                    bias_AAs_np=bias_AAs_np,
                    chain_M_pos=chain_M_pos,
                    omit_AA_mask=omit_AA_mask,
                    pssm_coef=pssm_coef,
                    pssm_bias=pssm_bias,
                    pssm_multi=0.0,
                    pssm_log_odds_flag=False,
                    pssm_log_odds_mask=(pssm_log_odds_all > 0.0).float(),
                    pssm_bias_flag=False,
                    tied_pos=tied_pos_list_of_lists_list[0],
                    tied_beta=tied_beta,
                    bias_by_res=bias_by_res_all,
                )

            S_sample = sample_dict["S"]

            # Score the sample
            log_probs_sample = model(
                X,
                S_sample,
                mask,
                chain_M * chain_M_pos,
                residue_idx,
                chain_encoding_all,
                randn_2,
                use_input_decoding_order=True,
                decoding_order=sample_dict["decoding_order"],
            )
            sample_scores, _ = _scores(S_sample, log_probs_sample, mask_for_loss)
            sample_score = float(sample_scores[0].cpu().numpy())

            # Get sample sequence
            sample_seq = _S_to_seq(S_sample[0], chain_M[0])

            # Format with chain separators
            start = 0
            list_of_AAs = []
            for mask_l in masked_chain_length_list:
                end = start + mask_l
                list_of_AAs.append(sample_seq[start:end])
                start = end
            sample_seq_formatted = "".join(
                list(np.array(list_of_AAs)[np.argsort(masked_list)])
            )
            l0 = 0
            for mc_length in list(
                np.array(masked_chain_length_list)[np.argsort(masked_list)]
            )[:-1]:
                l0 += mc_length
                sample_seq_formatted = (
                    sample_seq_formatted[:l0] + "/" + sample_seq_formatted[l0:]
                )
                l0 += 1

            # Calculate sequence recovery
            seq_recovery_per_res = (
                torch.sum(
                    torch.nn.functional.one_hot(S[0], 21)
                    * torch.nn.functional.one_hot(S_sample[0], 21),
                    axis=-1,
                )
                * mask_for_loss[0]
            )
            seq_recovery = float(
                torch.sum(seq_recovery_per_res) / torch.sum(mask_for_loss[0])
            )

            result["sequences"].append(
                {
                    "temperature": temperature,
                    "sample_index": 0,  # All from same batch
                    "score": sample_score,
                    "seq_recovery": seq_recovery,
                    "sequence": sample_seq_formatted,
                }
            )

    return result


def generate_probs_fixture(
    pdb_path: Path,
    model_name: str = "v_48_020",
    designable_res: str = "",
    unconditional: bool = False,
    seed: int = 42,
) -> dict:
    """Generate probability output using the original ProteinMPNN code.

    Args:
        pdb_path: Path to the PDB file
        model_name: Name of the model to use
        designable_res: Designable residue specification (empty = all residues)
        unconditional: If True, compute unconditional probs; otherwise conditional
        seed: Random seed for reproducibility

    Returns:
        Dictionary containing probability results and metadata
    """
    # Force CPU for cross-platform reproducibility
    device = torch.device("cpu")

    # Model hyperparameters
    hidden_dim = MODEL_CONFIG["hidden_dim"]
    num_layers = MODEL_CONFIG["num_layers"]

    # Load model weights
    model_weight_dir = determine_weight_directory()
    ckpt_path = os.path.join(model_weight_dir, f"{model_name}.pt")
    if not os.path.isfile(ckpt_path):
        raise ValueError(f"Model weights not found: {ckpt_path}")

    ckpt = torch.load(ckpt_path, map_location=device)
    num_edges = ckpt["num_edges"]

    # Build model
    model = ProteinMPNN(
        num_letters=21,
        node_features=hidden_dim,
        edge_features=hidden_dim,
        hidden_dim=hidden_dim,
        num_encoder_layers=num_layers,
        num_decoder_layers=num_layers,
        augment_eps=0.0,
        k_neighbors=num_edges,
    )
    model.to(device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    # Parse the PDB
    pdb_dir = pdb_path.parent
    pdb_name = pdb_path.stem
    pdb_ds = get_pdb_dataset(str(pdb_dir))

    # Find the correct protein
    protein = None
    for p in pdb_ds:
        if p["name"] == pdb_name:
            protein = p
            break
    if protein is None:
        protein = pdb_ds[0]

    # Extract chain sequences
    chain_sequences = {}
    for key in protein:
        if key.startswith("seq_chain_"):
            chain_id = key[-1]
            chain_sequences[chain_id] = protein[key]

    # Build design specs dict
    if designable_res:
        designable_list = parse_designable_res(designable_res, chain_sequences)
    else:
        # All residues designable
        designable_list = []
        for chain_id, seq in chain_sequences.items():
            for i, aa in enumerate(seq):
                designable_list.append({
                    "chain": chain_id,
                    "resid": i + 1,
                    "WTAA": aa,
                    "MutTo": "all",
                })

    design_specs_dict = {
        "sequence": chain_sequences,
        "designable": designable_list,
        "symmetric": [],
    }

    batch_clones = [copy.deepcopy(protein)]

    # Transform inputs
    (
        chain_id_dict,
        fixed_positions_dict,
        pssm_dict,
        omit_AA_dict,
        _,
        tied_positions_dict,
        bias_by_res_dict,
    ) = transform_inputs(design_specs_dict, protein, experimental=False)

    # Featurize
    (
        X,
        S,
        mask,
        _,
        chain_M,
        chain_encoding_all,
        letter_list_list,
        _,
        _,
        _,
        chain_M_pos,
        _,
        residue_idx,
        _,
        _,
        _,
        _,
        _,
        _,
        _,
    ) = tied_featurize(
        batch_clones,
        device,
        chain_id_dict,
        fixed_positions_dict,
        omit_AA_dict,
        tied_positions_dict,
        pssm_dict,
        bias_by_res_dict,
    )

    # Reset seed right before generating random tensor
    torch.manual_seed(seed)

    # Compute probabilities
    with torch.no_grad():
        if unconditional:
            log_probs = model.unconditional_probs(
                X,
                mask,
                residue_idx,
                chain_encoding_all,
            )
        else:
            randn = torch.randn(chain_M.shape, device=device)
            log_probs = model.conditional_probs(
                X,
                S,
                mask,
                chain_M * chain_M_pos,
                residue_idx,
                chain_encoding_all,
                randn,
            )

    # Extract results
    log_probs_np = log_probs[0].cpu().numpy()  # [L_padded, 21]
    mask_np = mask[0].cpu().numpy()

    # Get only valid (non-padded) positions
    valid_indices = mask_np > 0
    log_probs_valid = log_probs_np[valid_indices]

    # Build residue info
    chain_letters = letter_list_list[0]
    residue_info = []
    pos_in_protein = 0
    for chain_letter in chain_letters:
        chain_seq = protein[f"seq_chain_{chain_letter}"]
        chain_length = len(chain_seq)
        for res_idx in range(chain_length):
            if pos_in_protein < len(log_probs_valid):
                residue_info.append({
                    "chain": chain_letter,
                    "residue_idx": res_idx + 1,
                })
            pos_in_protein += 1

    mode = "unconditional" if unconditional else "conditional"

    return {
        "description": f"{mode.capitalize()} probs for {pdb_name} "
                       f"with seed={seed}, generated by ORIGINAL code. CPU-only.",
        "seed": seed,
        "model_name": model_name,
        "designable_res": designable_res,
        "mode": mode,
        "log_probs": log_probs_valid,
        "residue_info": residue_info,
        "num_residues": len(residue_info),
    }


def main():
    # Path setup
    fixtures_dir = ROOT_DIR / "tests" / "fixtures"
    data_dir = ROOT_DIR / "data" / "pdbs"
    pdb_path = data_dir / "6MRR.pdb"

    if not pdb_path.exists():
        print(f"ERROR: PDB file not found: {pdb_path}")
        sys.exit(1)

    # Generate 6MRR inference fixture
    print("=" * 60)
    print("Generating 6MRR inference fixture using original code...")
    print("=" * 60)

    result = generate_inference_fixture(
        pdb_path=pdb_path,
        designable_res="A1-A68",
        model_name="v_48_020",
        num_sequences=3,
        temperature=0.1,
        seed=42,
    )

    output_path = fixtures_dir / "6MRR_inference_original.json"
    with output_path.open("w") as f:
        json.dump(result, f, indent=2)

    print(f"Saved fixture to: {output_path}")
    print(f"  Native sequence: {result['native']['sequence']}")
    print(f"  Native score: {result['native']['score']:.6f}")
    print(f"  Designed chains: {result['native']['designed_chains']}")
    for i, seq in enumerate(result["sequences"]):
        print(
            f"  Sequence {i + 1}: score={seq['score']:.6f}, "
            f"recovery={seq['seq_recovery']:.4f}"
        )

    # Generate unconditional probs fixture
    print()
    print("=" * 60)
    print("Generating unconditional probs fixture using original code...")
    print("=" * 60)

    probs_result = generate_probs_fixture(
        pdb_path=pdb_path,
        model_name="v_48_020",
        designable_res="",  # All residues
        unconditional=True,
        seed=42,
    )

    # Save as npz for the array, json for metadata
    npz_path = fixtures_dir / "6MRR_unconditional_probs_original.npz"
    np.savez(
        npz_path,
        log_probs=probs_result["log_probs"],
    )
    json_path = fixtures_dir / "6MRR_unconditional_probs_original.json"
    metadata = {k: v for k, v in probs_result.items() if k != "log_probs"}
    with json_path.open("w") as f:
        json.dump(metadata, f, indent=2)

    print(f"Saved fixture to: {npz_path}")
    print(f"Saved metadata to: {json_path}")
    print(f"  Mode: {probs_result['mode']}")
    print(f"  Num residues: {probs_result['num_residues']}")
    print(f"  Log probs shape: {probs_result['log_probs'].shape}")

    # Generate conditional probs fixture (all residues designable)
    print()
    print("=" * 60)
    print("Generating conditional probs fixture (all residues)...")
    print("=" * 60)

    probs_result = generate_probs_fixture(
        pdb_path=pdb_path,
        model_name="v_48_020",
        designable_res="",  # All residues
        unconditional=False,
        seed=42,
    )

    npz_path = fixtures_dir / "6MRR_conditional_probs_all_original.npz"
    np.savez(
        npz_path,
        log_probs=probs_result["log_probs"],
    )
    json_path = fixtures_dir / "6MRR_conditional_probs_all_original.json"
    metadata = {k: v for k, v in probs_result.items() if k != "log_probs"}
    with json_path.open("w") as f:
        json.dump(metadata, f, indent=2)

    print(f"Saved fixture to: {npz_path}")
    print(f"Saved metadata to: {json_path}")
    print(f"  Mode: {probs_result['mode']}")
    print(f"  Num residues: {probs_result['num_residues']}")
    print(f"  Log probs shape: {probs_result['log_probs'].shape}")

    # Generate conditional probs fixture (partial designable)
    print()
    print("=" * 60)
    print("Generating conditional probs fixture (A1-A30 designable)...")
    print("=" * 60)

    probs_result = generate_probs_fixture(
        pdb_path=pdb_path,
        model_name="v_48_020",
        designable_res="A1-A30",
        unconditional=False,
        seed=42,
    )

    npz_path = fixtures_dir / "6MRR_conditional_probs_A1-A30_original.npz"
    np.savez(
        npz_path,
        log_probs=probs_result["log_probs"],
    )
    json_path = fixtures_dir / "6MRR_conditional_probs_A1-A30_original.json"
    metadata = {k: v for k, v in probs_result.items() if k != "log_probs"}
    with json_path.open("w") as f:
        json.dump(metadata, f, indent=2)

    print(f"Saved fixture to: {npz_path}")
    print(f"Saved metadata to: {json_path}")
    print(f"  Mode: {probs_result['mode']}")
    print(f"  Designable res: {probs_result['designable_res']}")
    print(f"  Num residues: {probs_result['num_residues']}")
    print(f"  Log probs shape: {probs_result['log_probs'].shape}")

    print()
    print("=" * 60)
    print("All fixtures generated successfully!")
    print("=" * 60)


if __name__ == "__main__":
    main()
